function [hNode,hString,hPipe1,hPipe2]=Construct(Ns,Nr,Node,Ini,color,hNode,hString,hPipe1,hPipe2)
% create a worm
if Ini; colorN='m'; else colorN='k'; end
for iN=1:Ns       % node plot
    for jN=1:3
        for kN=1:Nr
            hNode{iN,jN,kN}=plot3(Node(iN,jN,kN,1),Node(iN,jN,kN,2),...
                Node(iN,jN,kN,3),'Color',colorN,'Marker','.','MarkerSize',25);
        end
    end
end
for iP=1:Ns      % pipe&string plot
    for jP=1:3
        if iP==Ns&&jP==3; break;end
        if Ini; colorP='y';
        else colorP=[(3*(iP-1)+jP)/3/Ns,1-(3*(iP-1)+jP)/3/Ns,color];
        end
        for kP=1:Nr
            if ~Ini&&jP==2; hString{iP,kP}=plot3(...
                    [Node(iP,jP,kP,1),Node(iP,jP,mod(kP,Nr)+1,1)],...
                    [Node(iP,jP,kP,2),Node(iP,jP,mod(kP,Nr)+1,2)],...
                    [Node(iP,jP,kP,3),Node(iP,jP,mod(kP,Nr)+1,3)],...
                    'Color','b','LineWidth',1);
            end
            iP1=iP+floor(jP/3);
            jP1=mod(jP,3)+1;
            kP1=kP+(-1)^(iP+jP);
            kP2=kP1+Nr*(fix((Nr-kP1)/Nr)-fix(kP1/(Nr+1)));
            hPipe1{iP,jP,kP}=plot3(...
                [Node(iP,jP,kP,1),Node(iP1,jP1,kP,1)],...
                [Node(iP,jP,kP,2),Node(iP1,jP1,kP,2)],...
                [Node(iP,jP,kP,3),Node(iP1,jP1,kP,3)],...
                'Color',colorP,'LineWidth',2);
            hPipe2{iP,jP,kP}=plot3(...
                [Node(iP,jP,kP,1),Node(iP1,jP1,kP2,1)],...
                [Node(iP,jP,kP,2),Node(iP1,jP1,kP2,2)],...
                [Node(iP,jP,kP,3),Node(iP1,jP1,kP2,3)],...
                'Color',colorP,'LineWidth',2);
        end
    end
end